const fs = require('fs');
const path = require('path');

class MakefileGenerator {
  constructor(workspacePath, configManager) {
    this.workspacePath = workspacePath;
    this.configManager = configManager;
  }

  /**
   * Генерирует Makefile на основе конфигурации проекта
   */
  generateMakefile() {
    if (!this.workspacePath) return false;

    const projectConfig = this.configManager.projectConfig;
    const mcuParams = this.configManager.getMCUParams(projectConfig.mcu);
    
    // Получаем пути из конфигурации
    const startupFile = projectConfig.startupFile || mcuParams.startupFile;
    const ldscript = projectConfig.ldscript || 'STM32F407XX_FLASH.ld';

    const makefileContent = this.generateMakefileContent(
      projectConfig.projectName,
      startupFile,
      ldscript,
      mcuParams,
      projectConfig
    );

    const makefilePath = path.join(this.workspacePath, 'Makefile');
    const originalMakefilePath = path.join(this.workspacePath, 'Makefile.original');
    
    // Сохраняем оригинальный Makefile если его еще нет
    if (fs.existsSync(makefilePath) && !fs.existsSync(originalMakefilePath)) {
      fs.copyFileSync(makefilePath, originalMakefilePath);
      console.log('Оригинальный Makefile сохранен как Makefile.original');
    }

    try {
      fs.writeFileSync(makefilePath, makefileContent, 'utf8');
      console.log(`✅ Makefile успешно сгенерирован`);
      return true;
    } catch (error) {
      console.error('Ошибка записи Makefile:', error);
      return false;
    }
  }

  /**
   * Генерирует содержимое Makefile
   */
  generateMakefileContent(projectName, startupFile, ldscript, mcuParams, projectConfig) {
    // Создаем Makefile с правильными отступами (только табуляции, без пробелов)
    return `##########################################################################################################################
# File automatically-generated by STM32 Tools extension
# MCU: ${projectConfig.mcu || 'STM32F407VG'}
# Project: ${projectName}
# Startup: ${startupFile}.s
# Linker: ${ldscript}
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
# ------------------------------------------------

######################################
# target
######################################
TARGET = ${projectName}

######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og

#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \\
${projectConfig.sourceDirs.map(dir => `\t$(wildcard ${dir}/*.c)`).join(' \\\n')}

${projectConfig.excludeFiles && projectConfig.excludeFiles.length > 0 
    ? `\n# Filter out excluded files\nC_SOURCES := $(filter-out ${projectConfig.excludeFiles.map(f => `%${f}`).join(' ')}, $(C_SOURCES))` 
    : ''}

# ASM sources
ASM_SOURCES =  \\
\t${startupFile}.s

#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
CC = \$(PREFIX)gcc
AS = \$(PREFIX)gcc -x assembler-with-cpp
CP = \$(PREFIX)objcopy
SZ = \$(PREFIX)size
HEX = \$(CP) -O ihex
BIN = \$(CP) -O binary -S

#######################################
# CFLAGS
#######################################
# cpu
CPU = ${mcuParams.cpu}

# fpu
FPU = ${mcuParams.fpu}

# float-abi
FLOAT-ABI = ${mcuParams.floatAbi}

# mcu
MCU = \$(CPU) -mthumb \$(FPU) \$(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \\
\t-DUSE_HAL_DRIVER \\
\t-D${mcuParams.define}

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \\
${projectConfig.includeDirs.map(dir => `\t-I${dir}`).join(' \\\n')}

# compile gcc flags
ASFLAGS = \$(MCU) \$(AS_DEFS) \$(AS_INCLUDES) \$(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = \$(MCU) \$(C_DEFS) \$(C_INCLUDES) \$(OPT) -Wall -fdata-sections -ffunction-sections

ifeq (\$(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif

# Generate dependency information
CFLAGS += -MMD -MP -MF"\$(@:%.o=%.d)"

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = ${ldscript}

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = \$(MCU) -specs=nano.specs -T\$(LDSCRIPT) \$(LIBDIR) \$(LIBS) -Wl,-Map=\$(BUILD_DIR)/\$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: \$(BUILD_DIR)/\$(TARGET).elf \$(BUILD_DIR)/\$(TARGET).hex \$(BUILD_DIR)/\$(TARGET).bin

#######################################
# build the application
#######################################
# list of objects
OBJECTS = \$(addprefix \$(BUILD_DIR)/,\$(notdir \$(C_SOURCES:.c=.o)))
vpath %.c \$(sort \$(dir \$(C_SOURCES)))
# list of ASM program objects
OBJECTS += \$(addprefix \$(BUILD_DIR)/,\$(notdir \$(ASM_SOURCES:.s=.o)))
vpath %.s \$(sort \$(dir \$(ASM_SOURCES)))

\$(BUILD_DIR)/%.o: %.c Makefile | \$(BUILD_DIR) 
\t\$(CC) -c \$(CFLAGS) -Wa,-a,-ad,-alms=\$(BUILD_DIR)/\$(notdir \$(<:.c=.lst)) \$< -o \$@

\$(BUILD_DIR)/%.o: %.s Makefile | \$(BUILD_DIR)
\t\$(AS) -c \$(CFLAGS) \$< -o \$@

\$(BUILD_DIR)/\$(TARGET).elf: \$(OBJECTS) Makefile
\t\$(CC) \$(OBJECTS) \$(LDFLAGS) -o \$@
\t\$(SZ) \$@

\$(BUILD_DIR)/%.hex: \$(BUILD_DIR)/%.elf | \$(BUILD_DIR)
\t\$(HEX) \$< \$@

\$(BUILD_DIR)/%.bin: \$(BUILD_DIR)/%.elf | \$(BUILD_DIR)
\t\$(BIN) \$< \$@

\$(BUILD_DIR):
\tmkdir -p \$@

#######################################
# clean up
#######################################
clean:
\t-rm -fR \$(BUILD_DIR)

#######################################
# flash target
#######################################
flash: \$(BUILD_DIR)/\$(TARGET).bin
\tSTM32_Programmer_CLI -c port=SWD -w "\$<" -v -rst

#######################################
# dependencies
#######################################
-include \$(wildcard \$(BUILD_DIR)/*.d)

# *** EOF ***`;
  }

  /**
   * Обновляет существующий Makefile
   */
  updateMakefile() {
    const makefilePath = path.join(this.workspacePath, 'Makefile');
    if (!fs.existsSync(makefilePath)) {
      return this.generateMakefile();
    }

    try {
      const content = fs.readFileSync(makefilePath, 'utf8');
      
      // Проверяем, нужно ли обновлять
      const projectConfig = this.configManager.projectConfig;
      const mcuParams = this.configManager.getMCUParams(projectConfig.mcu);
      
      const startupFile = projectConfig.startupFile || mcuParams.startupFile;
      const ldscript = projectConfig.ldscript || 'STM32F407XX_FLASH.ld';
      
      // Проверяем актуальность startup файла
      const startupRegex = /ASM_SOURCES\s*=\s*[\\\s\S]*?(\S+\.s)/;
      const currentStartupMatch = content.match(startupRegex);
      const currentStartup = currentStartupMatch ? currentStartupMatch[1].replace('.s', '') : '';
      
      // Проверяем актуальность линкера
      const ldscriptRegex = /LDSCRIPT\s*=\s*(\S+)/;
      const currentLdscriptMatch = content.match(ldscriptRegex);
      const currentLdscript = currentLdscriptMatch ? currentLdscriptMatch[1] : '';
      
      // Если что-то изменилось, генерируем новый Makefile
      if (currentStartup !== startupFile || currentLdscript !== ldscript) {
        console.log('Makefile устарел, обновляю...');
        return this.generateMakefile();
      }
      
      console.log('Makefile актуален, обновление не требуется');
      return true;
    } catch (error) {
      console.error('Ошибка при проверке Makefile:', error);
      return this.generateMakefile();
    }
  }

  /**
   * Проверяет актуальность Makefile
   */
  checkMakefile() {
    const makefilePath = path.join(this.workspacePath, 'Makefile');
    if (!fs.existsSync(makefilePath)) {
      return { upToDate: false, message: 'Makefile не найден' };
    }

    try {
      const content = fs.readFileSync(makefilePath, 'utf8');
      const projectConfig = this.configManager.projectConfig;
      const mcuParams = this.configManager.getMCUParams(projectConfig.mcu);
      
      const startupFile = projectConfig.startupFile || mcuParams.startupFile;
      const ldscript = projectConfig.ldscript || 'STM32F407XX_FLASH.ld';
      
      // Проверяем актуальность startup файла
      const startupRegex = /ASM_SOURCES\s*=\s*[\\\s\S]*?(\S+\.s)/;
      const currentStartupMatch = content.match(startupRegex);
      const currentStartup = currentStartupMatch ? currentStartupMatch[1].replace('.s', '') : '';
      
      // Проверяем актуальность линкера
      const ldscriptRegex = /LDSCRIPT\s*=\s*(\S+)/;
      const currentLdscriptMatch = content.match(ldscriptRegex);
      const currentLdscript = currentLdscriptMatch ? currentLdscriptMatch[1] : '';
      
      const isUpToDate = currentStartup === startupFile && currentLdscript === ldscript;
      
      if (!isUpToDate) {
        return {
          upToDate: false,
          message: 'Makefile устарел',
          details: {
            currentStartup,
            expectedStartup: startupFile,
            currentLdscript,
            expectedLdscript: ldscript
          }
        };
      }
      
      return { upToDate: true, message: 'Makefile актуален' };
    } catch (error) {
      return { upToDate: false, message: `Ошибка проверки Makefile: ${error.message}` };
    }
  }
}

module.exports = MakefileGenerator;